### ISSUE TITLE
Explain how to use it

### ISSUE THREAD

**Issue by jorisw** [lkellar/nova-jsonformatter#2]
The README.md (displayed in the Nova preference panel) doesn't say anything about how to use this extension.

How do I format the JSON? Nothing happens on Save.

**Comment by lkellar** [comment]
Ah I'll add a note to the README.md. If you open up the command palette (⇧⌘P) and type Format JSON, you should see an option titled the same. Hitting that option should format the JSON

![CleanShot 2020-11-04 at 10 26 25](https://user-images.githubusercontent.com/28833934/98137971-3942d980-1e88-11eb-9789-39d94243cf24.png)
